export enum COMMON_STYLES {
  defaultFont = '"Open Sans", sans-serif',
  specialFont = '"Nunito", sans-serif',
  shadow = '0px 0 30px rgba(1, 41, 112, 0.1)',
  borderRadius = '5px',
  fontSizeSmall = '14px',
  fontSizeMedium = '18px',
  fontSizeLarge = '26px',
  fontWeightSmall = '400',
  fontWeightMedium = '500',
  fontWeightLarge = '600',
  fontWeightBold = '700',
  indentSmall = '10px',
  indentMedium = '20px',
  indentLarge = '40px',
}
